import type { Competitor } from "./types";

export const competitorsData: Competitor[] = [
  {
    id: 1,
    name: "clay",
    website: "http://clay.run/",
    social: "https://www.linkedin.com/in",
    industry: "MarTech",
    industryColor: "bg-[#F4EBE2] text-[#8C5D3E]",
    businessModel: "B2B SaaS / Product-led Growth",
    similarityScore: 96,
    hqLocation: "New York, NY",
    productType: "GTM Intelligence / AI Outreach",
    pricingStructure: "Credit-based / Freemium",
    employeeCount: "51-200",
    logoUrl: "https://www.google.com/s2/favicons?domain=clay.com&sz=128",
    faviconBg: "bg-gradient-to-tr from-[#EA580C] via-[#F43F5E] to-[#8B5CF6]",
    faviconText: "c",
    overview:
      "Clay is a GTM and sales intelligence platform that helps businesses discover prospects, enrich company and contact data, identify buying signals, and automate personalized outreach.",
    industryDetail: "MarTech / Sales Intelligence",
    companySize: "51-200 employees (estimated)",
    location: "New York, NY, United States",
    founded: "2017 (estimated)",
    offerings: [
      "Automated prospecting & enrichment",
      "AI email personalization & outreach",
      "Waterfall data provider orchestration",
    ],
  },
  {
    id: 2,
    name: "ramp",
    website: "http://ramp.com/",
    social: "https://www.linkedin.com/in",
    industry: "FinTech",
    industryColor: "bg-[#EFF6FF] text-[#2563EB]",
    businessModel: "Fintech / Interchange & SaaS",
    similarityScore: 91,
    hqLocation: "New York, NY",
    productType: "Spend Management & Cards",
    pricingStructure: "Free / Interchange-based",
    employeeCount: "501-1,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=ramp.com&sz=128",
    faviconBg: "bg-[#D9F99D] text-[#1E293B]",
    faviconText: "r",
    overview:
      "Ramp is an all-in-one corporate card and financial operations platform designed to help companies control spend, automate accounting, and optimize financial workflows.",
    industryDetail: "FinTech / Corporate Finance",
    companySize: "501-1,000 employees (estimated)",
    location: "New York, NY, United States",
    founded: "2019 (estimated)",
    offerings: [
      "Corporate charge cards & spend limits",
      "Automated expense management & receipt matching",
      "Procurement & vendor management workflows",
    ],
  },
  {
    id: 3,
    name: "Cursor",
    website: "https://cursor.com/",
    social: "https://www.linkedin.com/in",
    industry: "Developer Tools",
    industryColor: "bg-[#F5EFEA] text-[#8C5D3E]",
    businessModel: "Freemium / Developer SaaS",
    similarityScore: 94,
    hqLocation: "San Francisco, CA",
    productType: "AI Code Editor / IDE",
    pricingStructure: "Freemium / $20/mo Pro",
    employeeCount: "11-50",
    logoUrl: "https://www.google.com/s2/favicons?domain=cursor.com&sz=128",
    faviconBg: "bg-[#18181B]",
    faviconText: "C",
    overview:
      "Cursor is an AI-first code editor designed for pair-programming with AI, built on a fork of VS Code with smart auto-complete, multi-file editing, and natural language command execution.",
    industryDetail: "Developer Tools / AI Coding",
    companySize: "11-50 employees (estimated)",
    location: "San Francisco, CA, United States",
    founded: "2022 (estimated)",
    offerings: [
      "AI-native code editor & codebase indexing",
      "Multi-file conversational AI assistant",
      "Automated terminal command generation",
    ],
  },
  {
    id: 4,
    name: "plaid",
    website: "https://www.plaid.com/",
    social: "https://www.linkedin.com/in",
    industry: "FinTech",
    industryColor: "bg-[#EFF6FF] text-[#2563EB]",
    businessModel: "API / Consumption & Volume",
    similarityScore: 86,
    hqLocation: "San Francisco, CA",
    productType: "FinTech & Banking APIs",
    pricingStructure: "Usage-based / Custom",
    employeeCount: "1,001-5,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=plaid.com&sz=128",
    faviconBg: "bg-[#09090B]",
    faviconText: "p",
    overview:
      "Plaid provides financial services APIs that connect consumers, traditional financial institutions, and developers to easily share financial data and initiate bank payments.",
    industryDetail: "FinTech / Financial Infrastructure",
    companySize: "1,001-5,000 employees (estimated)",
    location: "San Francisco, CA, United States",
    founded: "2013 (estimated)",
    offerings: [
      "Secure bank account verification & linking",
      "Instant transaction data & balance checks",
      "Account-to-account payments infrastructure",
    ],
  },
  {
    id: 5,
    name: "ro",
    website: "https://ro.co/weight-loss/we/",
    social: "https://www.linkedin.com/in",
    industry: "HealthTech",
    industryColor: "bg-[#F5EEFB] text-[#8B44BC]",
    businessModel: "Direct-to-Consumer / Telehealth",
    similarityScore: 82,
    hqLocation: "New York, NY",
    productType: "Direct-to-Consumer Telehealth",
    pricingStructure: "Subscription + Medication",
    employeeCount: "501-1,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=ro.co&sz=128",
    faviconBg: "bg-transparent text-black font-semibold",
    faviconText: "ro",
    overview:
      "Ro is a direct-to-consumer digital healthcare technology company facilitating telehealth consultations, lab testing, and personalized treatment plans for weight loss and primary care.",
    industryDetail: "HealthTech / Telehealth",
    companySize: "501-1,000 employees (estimated)",
    location: "New York, NY, United States",
    founded: "2017 (estimated)",
    offerings: [
      "Direct-to-consumer telehealth consultations",
      "At-home diagnostic lab testing kits",
      "Nationwide prescription pharmacy delivery",
    ],
  },
  {
    id: 6,
    name: "airtable",
    website: "http://airtable.com/",
    social: "https://www.linkedin.com/in",
    industry: "B2B SaaS",
    industryColor: "bg-[#F5EEFB] text-[#8B44BC]",
    businessModel: "Product-led / B2B SaaS",
    similarityScore: 89,
    hqLocation: "San Francisco, CA",
    productType: "Low-Code Relational Database",
    pricingStructure: "Freemium / Per-seat Tiered",
    employeeCount: "501-1,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=airtable.com&sz=128",
    faviconBg: "bg-[#EF4444]",
    faviconText: "a",
    overview:
      "Airtable is a cloud-based low-code platform that combines the simplicity of a spreadsheet with the power of a relational database to build collaborative business workflows.",
    industryDetail: "B2B SaaS / Collaboration",
    companySize: "501-1,000 employees (estimated)",
    location: "San Francisco, CA, United States",
    founded: "2012 (estimated)",
    offerings: [
      "Relational database & spreadsheet interfaces",
      "Visual automation workflows & trigger actions",
      "Custom application builder for teams",
    ],
  },
  {
    id: 7,
    name: "amplitude",
    website: "https://amplitude.com/",
    social: "https://www.linkedin.com/in",
    industry: "Data & Analytics",
    industryColor: "bg-[#F0F4F8] text-[#486581]",
    businessModel: "Usage & Event-based SaaS",
    similarityScore: 85,
    hqLocation: "San Francisco, CA",
    productType: "Digital Product Analytics",
    pricingStructure: "Tiered / Event Volume",
    employeeCount: "501-1,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=amplitude.com&sz=128",
    faviconBg: "bg-[#0284C7]",
    faviconText: "A",
    overview:
      "Amplitude is a digital analytics platform that helps teams analyze user behavior, optimize digital product experiences, and drive growth through data-driven decisions.",
    industryDetail: "Data & Analytics / Product Intelligence",
    companySize: "501-1,000 employees (estimated)",
    location: "San Francisco, CA, United States",
    founded: "2012 (estimated)",
    offerings: [
      "Real-time user behavioral tracking & funnels",
      "Product feature experimentation & A/B testing",
      "Session replay & digital customer journey mapping",
    ],
  },
  {
    id: 8,
    name: "Scopely",
    website: "http://scopely.com/",
    social: "https://www.linkedin.com/in",
    industry: "Consumer",
    industryColor: "bg-[#FEF0EA] text-[#C05621]",
    businessModel: "Free-to-Play / In-App Monetization",
    similarityScore: 74,
    hqLocation: "Culver City, CA",
    productType: "Mobile Gaming & Live Ops",
    pricingStructure: "Free-to-Play + In-App",
    employeeCount: "1,001-5,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=scopely.com&sz=128",
    faviconBg: "bg-[#18181B]",
    faviconText: "✖",
    overview:
      "Scopely is an interactive entertainment company and mobile-first video game developer and publisher behind top-grossing global mobile franchise games.",
    industryDetail: "Consumer / Interactive Entertainment",
    companySize: "1,001-5,000 employees (estimated)",
    location: "Culver City, CA, United States",
    founded: "2011 (estimated)",
    offerings: [
      "Free-to-play mobile games & live operations",
      "Proprietary Playgami publishing platform",
      "Cross-platform gaming franchises",
    ],
  },
  {
    id: 9,
    name: "Solugen",
    website: "https://solugen.com/",
    social: "https://www.linkedin.com/in",
    industry: "CleanTech",
    industryColor: "bg-[#FDECF2] text-[#B83280]",
    businessModel: "Bio-industrial / B2B Contracts",
    similarityScore: 71,
    hqLocation: "Houston, TX",
    productType: "Bio-based Specialty Chemicals",
    pricingStructure: "Enterprise Contract",
    employeeCount: "101-250",
    logoUrl: "https://www.google.com/s2/favicons?domain=solugen.com&sz=128",
    faviconBg: "bg-[#18181B]",
    faviconText: "✱",
    overview:
      "Solugen is a sustainable chemical manufacturing company that replaces petroleum-based chemicals with plant-derived, bio-based alternatives using engineered enzymes.",
    industryDetail: "CleanTech / Bio-manufacturing",
    companySize: "101-250 employees (estimated)",
    location: "Houston, TX, United States",
    founded: "2016 (estimated)",
    offerings: [
      "Bio-based industrial chemical manufacturing",
      "Enzymatic chemi-catalytic Bioforge reactors",
      "Decarbonized water treatment & agriculture inputs",
    ],
  },
  {
    id: 10,
    name: "stripe",
    website: "http://stripe.com/",
    social: "https://www.linkedin.com/in",
    industry: "FinTech",
    industryColor: "bg-[#EFF6FF] text-[#2563EB]",
    businessModel: "Fintech / Transaction Processing",
    similarityScore: 88,
    hqLocation: "San Francisco, CA",
    productType: "Payments & Financial Infrastructure",
    pricingStructure: "Pay-as-you-go (2.9% + 30¢)",
    employeeCount: "5,001-10,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=stripe.com&sz=128",
    faviconBg: "bg-[#6366F1]",
    faviconText: "S",
    overview:
      "Stripe is a financial infrastructure platform for businesses, powering online payments, billing, invoicing, and treasury management worldwide.",
    industryDetail: "FinTech / Payments Infrastructure",
    companySize: "5,001-10,000 employees (estimated)",
    location: "San Francisco, CA & Dublin, Ireland",
    founded: "2010 (estimated)",
    offerings: [
      "Global online payment acceptance & checkout",
      "Subscription billing & recurring invoice automation",
      "Treasury & corporate card issuing APIs",
    ],
  },
  {
    id: 11,
    name: "warp",
    website: "https://warp.dev/",
    social: "https://www.linkedin.com/in",
    industry: "Developer Tools",
    industryColor: "bg-[#F5EFEA] text-[#8C5D3E]",
    businessModel: "Developer SaaS / Freemium",
    similarityScore: 92,
    hqLocation: "New York, NY",
    productType: "AI Command Terminal",
    pricingStructure: "Freemium / $12/user/mo",
    employeeCount: "11-50",
    logoUrl: "https://www.google.com/s2/favicons?domain=warp.dev&sz=128",
    faviconBg: "bg-[#09090B]",
    faviconText: ">",
    overview:
      "Warp is a modern, Rust-based terminal with built-in AI assistance, collaborative workflows, and a block-based command execution interface.",
    industryDetail: "Developer Tools / Terminal",
    companySize: "11-50 employees (estimated)",
    location: "New York, NY, United States",
    founded: "2020 (estimated)",
    offerings: [
      "Rust-based GPU-accelerated command terminal",
      "Built-in AI command lookup & execution debugging",
      "Team command workflows & shared runbooks",
    ],
  },
  {
    id: 12,
    name: "Zipline",
    website: "http://www.flyzipline.com/",
    social: "https://www.linkedin.com/in",
    industry: "Logistics & Supply Chain",
    industryColor: "bg-[#FBF1E6] text-[#A25F2A]",
    businessModel: "Autonomous Logistics / HaaS",
    similarityScore: 78,
    hqLocation: "South San Francisco, CA",
    productType: "Autonomous Drone Logistics",
    pricingStructure: "Enterprise Contract / Delivery",
    employeeCount: "501-1,000",
    logoUrl: "https://www.google.com/s2/favicons?domain=flyzipline.com&sz=128",
    faviconBg: "bg-[#DC2626]",
    faviconText: "Z",
    overview:
      "Zipline is an automated logistics and autonomous drone delivery system company delivering medical supplies, vaccines, and commercial packages on demand.",
    industryDetail: "Robotics / Autonomous Logistics",
    companySize: "501-1,000 employees (estimated)",
    location: "South San Francisco, CA, United States",
    founded: "2014 (estimated)",
    offerings: [
      "Autonomous aerial drone delivery networks",
      "Instant medical supply & blood delivery logistics",
      "Platform 2 precision urban package delivery",
    ],
  },
];

